version: "3"

services:
  web:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - "./counter:/var/www/html"
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Test2022?!
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
  adminer:
    image: adminer
    ports:
      - 8081:8080