version: "3"

services:
  web:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - 8080:80
    links:
      - mariadb
    volumes:
      - "./counter:/var/www/html"
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: Test2022?!
  adminer:
    image: adminer
    ports:
      - 8081:8080